[package]
name = "restless"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Patrick M. Elsen <pelsen@xfbs.net>"]
description = "REST API helper traits"
repository = "https://github.com/xfbs/restless"

[dependencies]
async-trait = { version = "0.1.72", optional = true }
bincode = { version = "1.3.3", optional = true }
bytes = { version = "1.4.0", optional = true }
gloo-net = { version = "0.3.1", optional = true }
postcard = { version = "1.0.6", optional = true, features = ["alloc"] }
serde = { version = "1.0.183", optional = true }
serde_json = { version = "1.0.104", optional = true }
serde_qs = { version = "0.12.0", optional = true }
serde_urlencoded = { version = "0.7.1", optional = true }
serde_yaml = { version = "0.9.25", optional = true }
url = "2.4.0"

[features]
default = ["bytes", "json"]
json = ["dep:serde_json", "serde"]
bytes = ["dep:bytes"]
postcard = ["dep:postcard", "serde"]
bincode = ["dep:bincode", "serde"]
yaml = ["dep:serde_yaml", "serde"]
urlencoded = ["dep:serde_urlencoded", "serde"]
qs = ["dep:serde_qs", "serde"]
gloo = ["dep:gloo-net", "json"]
yew = []
reqwest = []
