[package]
name = "restless-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1.5.0", optional = true }
thiserror = "1.0.57"

[features]
bytes = ["dep:bytes"]

[package.metadata.docs.rs]
features = ["bytes"]
