[package]
name = "restless-wasm-cache"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.77"
restless-gloo.workspace = true
wasm-cache = { version = "0.1.1", git = "https://github.com/xfbs/wasm-cache" }
